// Generated by LiveScript 1.3.1
(function(){
  var fs, jsYaml, readFileSync, writeFileSync;
  fs = require('fs');
  jsYaml = require('js-yaml');
  readFileSync = function(filename){
    return jsYaml.safeLoad(fs.readFileSync(filename, 'utf-8'));
  };
  writeFileSync = function(filename, data){
    return fs.writeFileSync(filename, jsYaml.safeDump(data));
  };
  if ((typeof module != 'undefined' && module !== null) && module.exports != null) {
    module.exports = {
      read: readFileSync,
      readSync: readFileSync,
      readFileSync: readFileSync,
      write: writeFileSync,
      writeSync: writeFileSync,
      writeFileSync: writeFileSync
    };
  }
}).call(this);
